### ISSUE TITLE
about g_spawn_close_pid

### ISSUE THREAD

**Issue by guyuming76** [padgettr/rfm#4]
i see you use G_SPAWN_DO_NOT_REAP_CHILD flag:

https://github.com/padgettr/rfm/blob/76fed73021058aad0d4c184cd94a9483be940734/rfm.c#L635

and you use g_child_watch_add
https://docs.gtk.org/glib/func.child_watch_add.html 

and in the handler, i see no calling to g_spawn_close_pid.

but when i debug the code, i see child process disappear in htop instead of becoming zombie.

That's what i cannot understand, something special with my system configuration or gtk change from version 2 to version 3?

**Comment by padgettr** [comment]
Hi, you are having a good look through the code, I appreciate that, thankyou for your time and interest!

It is my understanding that g_child_watch_add () automatically waits for the child and you must not call any of the wait functions on the child. It's not very explicit in the glib2 docs, but under g_child_watch_source_new () (called by g_child_watch_add () ) we have:


On POSIX platforms, the following restrictions apply to this API due to limitations in POSIX process interfaces:

  *   pid must be a child of this process

  *   pid must be positive

  *   the application must not call waitpid with a non-positive first argument, for instance in another thread

  *   the application must not wait for pid to exit by any other mechanism, including waitpid(pid, ...) or a second child-watch source for the same pid

  *   the application must not ignore SIGCHLD

So on POSIX, g_child_watch_add() will call wait for you and reap the child. This is not the case on windows - I believe there you must call g_spawn_close_pid() to free the returned handle. So I don't think you have to call g_spawn_close_pid() unless on windows. However, I realise this is not best practice, and under g_spawn_close_pid() we have:

On some platforms, notably Windows, the GPid<glib-The-Main-Event-Loop.html#GPid> type represents a resource which must be closed to prevent resource leaking. g_spawn_close_pid()<glib-Spawning-Processes.html#g-spawn-close-pid> is provided for this purpose. It should be used on all platforms, even though it doesn't do anything under UNIX.

So I'm inclined to add this in as you suggest. Although it won't run on windows in its current state (there are system calls specific to linux in the code, e.g. inotify) there is no reason it couldn't as glib provides wrappers around most system calls which will function on windows or linux.

Regarding the threading, I had a bit of spare time last night and reverted the threading stuff. Instead I added in a simple g_idle_timer for both dir read and thumbnailing. I've been using it this morning and can't see any difference in reponsiveness, even on my slow connection to work drives. I think the main slowness here is updating iconview itself - there's no point in the other bits being faster than that. I'm inclined to drop the multithread as it is a headache! I haven't pushed any changes to git yet though, I'd like to test it a bit more. If thumbnailing huge images it could become unresponsive (I sometimes have images 100M+, but then there is threadpools in glib which I think could handle thumbnailing...



________________________________
From: guyuming ***@***.***>
Sent: 12 October 2022 04:00
To: padgettr/rfm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [padgettr/rfm] about g_spawn_close_pid (Issue #4)


i see you use G_SPAWN_DO_NOT_REAP_CHILD flag:

https://github.com/padgettr/rfm/blob/76fed73021058aad0d4c184cd94a9483be940734/rfm.c#L635

and you use g_child_watch_add
https://docs.gtk.org/glib/func.child_watch_add.html

and in the handler, i see no calling to g_spawn_close_pid.

but when i debug the code, i see child process disappear in htop instead of becoming zombie.

That's what i cannot understand, something special with my system configuration or gtk change from version 2 to version 3?
