### ISSUE TITLE
focus go to first item on icon or tree view after item_activated

### ISSUE THREAD

**Issue by guyuming76** [padgettr/rfm#7]
no matter in IconView, or in the ListView i added, i can press Enter on a selected item to open it. The method item_activated will be called, which will run action based on MIME. For example, if i press enter on a png file, script will be run to refresh IMV image viewer.

but the problem is, after press enter and item_actived called, the current specific item will lost selection and focus. The focus will go to the first item in IconView or ListView. So, if i need to open the next image, i always need to press the down arrow key from the beginning of the view. I don't know if this is the default. behavior of gtk view. Can this be configured?   

In screenshots below, i am trying to see what happens in rfm with G_MESSAGE_DEBUG, but no useful results.  The upper right panel in DWL stack zone is IMV, the middle right zone in DWL stack zone is rfm.

![20230506_10h13m37s_grim](https://user-images.githubusercontent.com/12045548/236629487-319bf081-38a6-45ef-bf68-0c7435374777.png)
![20230506_10h12m58s_grim](https://user-images.githubusercontent.com/12045548/236629576-498fad39-757a-498a-a1ab-9e2207660427.png)

**Comment by padgettr** [comment]
This doesn't happen for me, but it could happen depending on what command is activated. There is an inotify watch placed on the current directory. If the command you run triggers inotify (for example creates a file) then the dir will be re-read, and the icon-view will reset. This is not because of icon-view, its the way the filer works - it refreshes the entire view if something in the current dir changes.

There are 2 things you could do I think:

1. Change rfm behaviour to only update the iconview for file changes in the current dir, rather than refresh the whole view. It does this already under certain circumstances, e.g. when copying many files there is a timeout before a full refresh. You would need to make sure row references remain valid if the model changes.

2. Keep track of the selected item before running a command and restore the selection afterwards, if required. The selection would need restoring during dir read, there is already some code that restores a previous dir selection when you move up one dir, maybe you could build on that.

Hope that helps, cheers, Rod.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: guyuming ***@***.***>
Sent: Saturday, May 6, 2023 3:31:51 PM
To: padgettr/rfm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [padgettr/rfm] focus go to first item on icon or tree view after item_activated (Issue #7)


no matter in IconView, or in ListView i added, i can press enter on a selected item to open it. The method item_activated will be called, which will call run_action based on item MIME. For example, if i press enter on a png file, script will be run to refresh IMV image viewer.

but the problem is, after press enter and item_actived, the current specific item will lost selection and focus. The focus will go to the first item in IconView or ListView. So, if i need to open the next image, i always need to press the down arrow key from the beginning of the view. I don't know if this is the default behavior of gtk view. Can this be configured?

[20230506_10h13m37s_grim]<https://user-images.githubusercontent.com/12045548/236629487-319bf081-38a6-45ef-bf68-0c7435374777.png>
[20230506_10h12m58s_grim]<https://user-images.githubusercontent.com/12045548/236629576-498fad39-757a-498a-a1ab-9e2207660427.png>

**Comment by guyuming76** [comment]
@padgettr , I tried another computer with the same rfm code, except gtk+ version is a little bit different, and it works without problem.

On the problematic machine, i also tried sys-prof. i got some .syscap files, but don't know how to find out what is the code that lead to the abnormal behavior.

with lsof on the working machine, i can see /usr/lib64/libgtk-3.so.0.2404.30 is loaded by rfm;
for the problematic machine, /usr/lib64/libgtk-3.so.0.2405.32

but i need a way to figure out the exact lines of code that cause the difference.


The run_action triggered has nothing to do with inotify_hander, it only send some inter-process message to IMV to change the displaying picture.

**Comment by padgettr** [comment]
I'm also using libgtk-3.so.0.2405.32 but I don't have the issue (arch linux). After item_activated is called by the signal, there are no iconview functions called, only functions to get the tree path. So if inotify is not triggered I'm not sure what could be causing this. Have you tried running the iconview demo in gtk3-demos (icon View -> Icon View Basics)? Does it happen on the demo if you just pick a file (the demo doesn't do anything with files, but it does still connect to item_activated).

**Comment by guyuming76** [comment]
There is also something strange with G_ENABLE_DEBUG on my problematic machine https://forums.gentoo.org/viewtopic-p-8788681.html#8788681, although i don't know whether G_ENABLE_DEBUG would help me to find out what caused the different behavior after item_activated on different machine.

**Comment by guyuming76** [comment]
@padgettr , you are right at the beginning, it is because of the inotify handler. simply set breakpoint in gdb can show this, it is the gmon.out file created in current working directory which triggered the handler.
![20230518_13h58m36s_grim](https://github.com/padgettr/rfm/assets/12045548/ecaf7880-4b6a-45ae-8d3d-b5fbc1296a48)
![20230518_14h12m41s_grim](https://github.com/padgettr/rfm/assets/12045548/fe3dedbc-c707-4022-b981-9ff2801decf2)

**Comment by padgettr** [comment]
The inotify code is quite old, and there are a few bugs although I've never had a problem before. Normally the only issue is if the thumbnail glist gets out of sync with the current model. Probably should use g_file_monitor now, see
https://docs.gtk.org/gio/method.File.monitor_directory.html
This would be good for portability (I have used it on a windows gtk app once and it worked well) and probably more robust than the old inotify code. Might also work on /sys and /proc (although I haven't tried this).

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
